language: node_js
sudo: required
services:
  - docker
cache:
   directories:
     - node_modules
node_js:
  - 9.1
before_install:
  - docker network create disocovery
script:
  - npm test
after_install:
  - docker network rm discovery
