version: '3.1'

services:

  api-facade:
    container_name: api-facade
    build:
      context: .
      args:
        - NODE_ENV=dev
    volumes:
      - './src:/usr/src/app/src'
      - './test:/usr/src/app/test'
    ports:
      - '3000:3000'

networks:
  default:
    external:
      name: discovery
