version: '3.1'

services:

  api-facade:
    container_name: api-facade
    build:
      context: .
      args:
        - NODE_ENV=dev
    volumes:
      - './src:/usr/src/app/src'
      - './test:/usr/src/app/test'
    ports:
      - '3000:3000'
    environment:
      DISCOVERY_DNS: consul

  consul:
    build:
      context: ./consul/
    ports:
      - "8300"
      - "8301"
      - "8400"
      - "8500:8500"
      - "53"
      - "53/udp"
    command:
      - agent
      - -dev
      - -ui
      - -bind
      - 0.0.0.0
      - -client
      - 0.0.0.0
      - -dns-port
      - "53"
      - -recursor
      - 8.8.8.8

networks:
  default:
    external:
      name: discovery
