version: '3.1'

services:

  api-facade:
    container_name: api-facade
    build:
      context: ./facade/
      args:
        - NODE_ENV=dev
    ports:
      - '5000:5000'

networks:
  default:
    external:
      name: discovery
